#!/bin/sh
# Build the web (WebAssembly) version of the game into web/dist/
#
# This is deliberately NOT part of Maekfile.js: Maek's CPP/LINK assume a native
# toolchain, and teaching it a second one buys nothing. This runs by hand, on a
# laptop, about once per release.
#
# Output: web/dist/droplet.{html,js,wasm}. Those three files needed to be copied into the
# portfolio repo at public/games/droplet/ to publish.

set -e

# emcc/em++ are not on PATH by default; emsdk_env.sh puts them there.
# Override the location with:  EMSDK=/path/to/emsdk sh build-web.sh
if ! command -v em++ > /dev/null 2>&1; then
	. "${EMSDK:-$HOME/Developer/Environments/emsdk}/emsdk_env.sh"
fi

# extract_sprite is a native program, so asset.hpp has to be regenerated by the
# normal build before emcc ever sees PlayMode.cpp:
node Maekfile.js :assets

mkdir -p web/dist

# Excluded on purpose:
#   GL.cpp          -- emscripten links GL entry points directly; nothing to look up
#   load_save_png.cpp -- only the PrintScreen handler used it, and that is #ifdef'd out
#   data_path.cpp   -- has an #error for unknown OS, and nothing in the game calls data_path()
# em++ rather than emcc: emcc links without libc++ (same distinction as clang vs clang++).
# -O2 strips every newline from the generated html/js; MINIFY_HTML=0 and -g2 keep both
# readable (-g2 also keeps js function names). Neither affects the wasm's speed.
em++ \
	PlayMode.cpp \
	PPU466.cpp \
	main.cpp \
	Mode.cpp \
	Load.cpp \
	gl_compile_program.cpp \
	-I../nest-libs/macos/glm/include \
	--use-port=sdl3 \
	-sMIN_WEBGL_VERSION=2 -sMAX_WEBGL_VERSION=2 \
	-sALLOW_MEMORY_GROWTH=1 \
	-O2 -std=c++20 -Wall \
	-sMINIFY_HTML=0 \
	-g2 \
	--shell-file web/shell.html \
	-o web/dist/droplet.html

# the page shows a screenshot, so it has to sit next to droplet.html:
cp screenshots/screenshot-win.png web/dist/

echo ""
echo "Built:"
ls -la web/dist
