#include <iostream>
#include <fstream>
#include <array>
#include <vector>
#include <string>

#include <glm/glm.hpp>

#include "load_save_png.hpp"
#include "PPU466.hpp"

//--------------------------------------------------------------
typedef std::array< glm::u8vec4, 4 > Palette;

const std::array< Palette, 6 > palette_table = {{
	{ //0: background
		glm::u8vec4(0x05,0x08,0x16,0xff),
		glm::u8vec4(0x7d,0xd3,0xfc,0xff),
		glm::u8vec4(0x16,0x4a,0x70,0xff),
		glm::u8vec4(0x5c,0x8f,0x7b,0xff),
	},
	{ //1: droplet
		glm::u8vec4(0x00,0x00,0x00,0x00),
		glm::u8vec4(0xae,0xb4,0xba,0xff),
		glm::u8vec4(0xf4,0xf7,0xfa,0xff),
		glm::u8vec4(0xf4,0xf7,0xfa,0xff),
	},
	{ //2: star (small + bright)
		glm::u8vec4(0x00,0x00,0x00,0x00),
		glm::u8vec4(0xfb,0xbf,0x24,0xff),
		glm::u8vec4(0xff,0xf7,0xd6,0xff),
		glm::u8vec4(0xd9,0x77,0x06,0xff),
	},
	{ //3: meteorite (small + large)
		glm::u8vec4(0x00,0x00,0x00,0x00),
		glm::u8vec4(0x6b,0x62,0x5c,0xff),
		glm::u8vec4(0x2b,0x25,0x23,0xff),
		glm::u8vec4(0xb7,0xaa,0x9b,0xff),
	},
	{ //4: spacecraft body
		glm::u8vec4(0x00,0x00,0x00,0x00),
		glm::u8vec4(0x16,0x1b,0x35,0xff),
		glm::u8vec4(0x65,0x73,0x8e,0xff),
		glm::u8vec4(0xbf,0xe3,0xea,0xff),
	},
	{ //5: spacecraft other parts
		glm::u8vec4(0x00,0x00,0x00,0x00),
		glm::u8vec4(0x16,0x1b,0x35,0xff),
		glm::u8vec4(0x65,0x73,0x8e,0xff),
		glm::u8vec4(0xff,0xb3,0x47,0xff),
	},
}};

//one asset = one PNG + the list of palette_table indices its tiles are allowed to use
struct AssetInfo {
	std::string name;
	std::string path;
	std::vector< uint8_t > candidate_palettes;
};

const std::array< AssetInfo, 6 > assets = {{
	{ "droplet",           "assets/droplet-16-16.png",            {1} },
	{ "human_spacecraft",  "assets/human-spacecraft-48-24.png",    {4, 5} },
	{ "star_small",        "assets/small-star-8-8.png",            {2} },
	{ "star_bright",       "assets/bright-star-16-16.png",         {2} },
	{ "meteorite_small",   "assets/meteorite-small-16-16.png",     {3} },
	{ "meteorite_large",   "assets/meteorite-large-24-24.png",     {3} },
}};

//find which palette (by index into `palette_table`) can render all colors in `colors`
// returns -1 if none of `candidates` work.
int32_t find_palette(std::vector< glm::u8vec4 > const &colors, std::vector< uint8_t > const &candidates) {
	for (uint8_t p : candidates) {
		Palette const &pal = palette_table[p];
		bool all_found = true;
		for (auto const &c : colors) {
			bool found = false;
			for (auto const &pc : pal) {
				if (pc == c) { found = true; break; }
			}
			if (!found) { all_found = false; break; }
		}
		if (all_found) return int32_t(p);
	}
	return -1;
}

//pack the 8x8 block at tile (tx,ty) into a PPU466::Tile using `pal`.
// (assumes every pixel in the block appears in `pal` -- check with find_palette first.)
PPU466::Tile pack_tile(std::vector< glm::u8vec4 > const &pixels, glm::uvec2 const &size,
                       uint32_t tx, uint32_t ty, Palette const &pal) {
	PPU466::Tile tile;
	for (uint32_t y = 0; y < 8; ++y) {
		uint8_t bit0 = 0, bit1 = 0;
		for (uint32_t x = 0; x < 8; ++x) {
			glm::u8vec4 c = pixels[(tx*8+x) + size.x*(ty*8+y)];
			uint32_t idx = 0;
			for (; idx < 4; ++idx) if (pal[idx] == c) break;
			if (idx & 1) bit0 |= (1 << x);
			if (idx & 2) bit1 |= (1 << x);
		}
		tile.bit0[y] = bit0;
		tile.bit1[y] = bit1;
	}
	return tile;
}

//gather the distinct colors used by the 8x8 block at tile (tx,ty):
std::vector< glm::u8vec4 > tile_colors(std::vector< glm::u8vec4 > const &pixels, glm::uvec2 const &size,
                                       uint32_t tx, uint32_t ty) {
	std::vector< glm::u8vec4 > used;
	for (uint32_t y = 0; y < 8; ++y) {
		for (uint32_t x = 0; x < 8; ++x) {
			glm::u8vec4 c = pixels[(tx*8+x) + size.x*(ty*8+y)];
			bool seen = false;
			for (auto const &u : used) if (u == c) { seen = true; break; }
			if (!seen) used.push_back(c);
		}
	}
	return used;
}

//write a byte as a readable 8-bit literal for debugging, e.g. 0b01111110
std::string binary_literal(uint8_t b) {
	std::string s = "0b";
	for (uint32_t i = 8; i > 0; --i) {
		s += ((b >> (i-1)) & 1) ? '1' : '0';
	}
	return s;
}

//--------------------------------------------------------------
int main(int argc, char **argv) {
	std::ofstream out("asset.hpp");
	out << "#pragma once\n";
	out << "//AUTO-GENERATED by extract_sprite.cpp \n";
	out << "\n";
	out << "#include \"PPU466.hpp\" \n";
	out << "\n";

	{ //palettes: copy these into ppu.palette_table[0..5]
		out << "const std::array< PPU466::Palette, " << palette_table.size() << " > asset_palettes = {{\n";
		for (uint32_t p = 0; p < palette_table.size(); ++p) {
			out << "\t{ //palette " << p << "\n";
			for (auto const &c : palette_table[p]) {
				out << "\t\tglm::u8vec4(0x" << std::hex << uint32_t(c.r)
				    << ", 0x" << uint32_t(c.g)
				    << ", 0x" << uint32_t(c.b)
				    << ", 0x" << uint32_t(c.a) << "),\n" << std::dec;
			}
			out << "\t},\n";
		}
		out << "}};\n\n";
	}

	uint32_t next_tile_index = 0; //assets are packed into tile_table in order

	for (auto const &asset : assets) {
		glm::uvec2 size;
		std::vector< glm::u8vec4 > pixels;
		load_png(asset.path, &size, &pixels, OriginLocation::LowerLeftOrigin);

		if (size.x % 8 != 0 || size.y % 8 != 0) {
			std::cerr << "ERROR: " << asset.path << " is " << size.x << "x" << size.y
			          << ", not a multiple of 8x8." << std::endl;
			return 1;
		}

        // if a sprite consists of multiple tiles
		uint32_t tiles_x = size.x / 8;
		uint32_t tiles_y = size.y / 8;

		uint32_t tile_count = tiles_x * tiles_y;
		if (next_tile_index + tile_count > 256) {
			std::cerr << "ERROR: ran out of tile_table slots at " << asset.path << std::endl;
			return 1;
		}

		out << "//" << asset.name << ": " << tiles_x << "x" << tiles_y << " tiles, "
		    << "occupies tile_table[" << next_tile_index << ".." << (next_tile_index + tile_count - 1) << "]\n";
		out << "const uint8_t " << asset.name << "_tile_index = " << next_tile_index << ";\n";
		out << "const uint32_t " << asset.name << "_tiles_x = " << tiles_x << ";\n";
		out << "const uint32_t " << asset.name << "_tiles_y = " << tiles_y << ";\n";
		out << "const std::array< PPU466::Tile, " << tile_count << " > " << asset.name << "_tiles = {{\n";

		std::string palette_line = "const std::array< uint8_t, " + std::to_string(tile_count) + " > "
		                         + asset.name + "_tile_palettes = {{ ";

		next_tile_index += tile_count;

		for (uint32_t ty = 0; ty < tiles_y; ++ty) {
			for (uint32_t tx = 0; tx < tiles_x; ++tx) {
				//gather this tile's distinct colors
				std::vector< glm::u8vec4 > used;
				for (uint32_t y = 0; y < 8; ++y) {
					for (uint32_t x = 0; x < 8; ++x) {
						glm::u8vec4 c = pixels[(tx*8+x) + size.x*(ty*8+y)];
						bool seen = false;
						for (auto const &u : used) if (u == c) { seen = true; break; }
						if (!seen) used.push_back(c);
					}
				}

				int32_t pal_index = find_palette(used, asset.candidate_palettes);
				if (pal_index < 0) {
					std::cerr << "ERROR: " << asset.path << " tile (" << tx << "," << ty << ") "
					          << "uses " << used.size() << " colors that don't fit any candidate palette."
					          << std::endl;
					return 1;
				}
				Palette const &pal = palette_table[pal_index];

				//pack pixel colors into bit0/bit1 using this tile's matched palette:
				PPU466::Tile tile;
				for (uint32_t y = 0; y < 8; ++y) {
					uint8_t bit0 = 0, bit1 = 0;
					for (uint32_t x = 0; x < 8; ++x) {
						glm::u8vec4 c = pixels[(tx*8+x) + size.x*(ty*8+y)];
						uint32_t idx = 0;
						for (; idx < 4; ++idx) if (pal[idx] == c) break;
						if (idx & 1) bit0 |= (1 << x);
						if (idx & 2) bit1 |= (1 << x);
					}
					tile.bit0[y] = bit0;
					tile.bit1[y] = bit1;
				}

				//emit one Tile, laid out like PlayMode.cpp's hand-written tiles:
				out << "\t{ //tile (" << tx << "," << ty << "), palette " << pal_index << "\n";
				//NOTE: rows go in storage order (element 0 = BOTTOM row, per PPU466.hpp),
				// so these read bottom-up -- i.e. upside down compared to the source art.
				out << "\t\t{ //bit0\n";
				for (uint32_t y = 0; y < 8; ++y) {
					out << "\t\t\t" << binary_literal(tile.bit0[y]) << ",\n";
				}
				out << "\t\t},\n";
				out << "\t\t{ //bit1\n";
				for (uint32_t y = 0; y < 8; ++y) {
					out << "\t\t\t" << binary_literal(tile.bit1[y]) << ",\n";
				}
				out << "\t\t},\n";
				out << "\t},\n";

				palette_line += std::to_string(uint32_t(pal_index)) + ", ";
			} //end tile
		}
		out << "}};\n";
		out << palette_line << "}};\n\n";
	} //end asset

	{ //background: unlike sprites, this fills ppu.background[] -- a 64x60 grid of
	  // tile-index + palette-index. Identical 8x8 blocks are deduplicated so a
	  // 3840-cell map only costs a handful of tile_table slots.
		const std::string path = "assets/space-earth-background-preview-512-480.png";
		const uint8_t background_palette = 0;

		glm::uvec2 size;
		std::vector< glm::u8vec4 > pixels;
		load_png(path, &size, &pixels, OriginLocation::LowerLeftOrigin);

		if (size.x != PPU466::BackgroundWidth * 8 || size.y != PPU466::BackgroundHeight * 8) {
			std::cerr << "ERROR: " << path << " is " << size.x << "x" << size.y
			          << ", expected " << (PPU466::BackgroundWidth*8) << "x" << (PPU466::BackgroundHeight*8)
			          << "." << std::endl;
			return 1;
		}

		//dedup tiles; unique_tiles[i] gets tile_table slot (base + i):
		std::vector< PPU466::Tile > unique_tiles;
		std::vector< uint16_t > map(PPU466::BackgroundWidth * PPU466::BackgroundHeight, 0);

		for (uint32_t ty = 0; ty < PPU466::BackgroundHeight; ++ty) {
			for (uint32_t tx = 0; tx < PPU466::BackgroundWidth; ++tx) {
				std::vector< glm::u8vec4 > used = tile_colors(pixels, size, tx, ty);
				if (find_palette(used, {background_palette}) < 0) {
					std::cerr << "ERROR: " << path << " tile (" << tx << "," << ty << ") "
					          << "uses " << used.size() << " colors that don't fit palette "
					          << uint32_t(background_palette) << "." << std::endl;
					return 1;
				}
				PPU466::Tile tile = pack_tile(pixels, size, tx, ty, palette_table[background_palette]);

				uint32_t slot = 0;
				for (; slot < unique_tiles.size(); ++slot) {
					if (unique_tiles[slot].bit0 == tile.bit0 && unique_tiles[slot].bit1 == tile.bit1) break;
				}
				if (slot == unique_tiles.size()) unique_tiles.push_back(tile);

				map[tx + PPU466::BackgroundWidth*ty] = uint16_t((next_tile_index + slot) | (background_palette << 8));
			}
		}

		if (next_tile_index + unique_tiles.size() > 256) {
			std::cerr << "ERROR: ran out of tile_table slots for background ("
			          << unique_tiles.size() << " unique tiles needed)." << std::endl;
			return 1;
		}

		out << "//background: " << PPU466::BackgroundWidth << "x" << PPU466::BackgroundHeight
		    << " cells, " << unique_tiles.size() << " unique tiles, "
		    << "occupies tile_table[" << next_tile_index << ".." << (next_tile_index + unique_tiles.size() - 1) << "]\n";
		out << "const uint8_t background_tile_index = " << next_tile_index << ";\n";
		out << "const std::array< PPU466::Tile, " << unique_tiles.size() << " > background_tiles = {{\n";
		for (uint32_t i = 0; i < unique_tiles.size(); ++i) {
			out << "\t{ //unique tile " << i << " -> tile_table[" << (next_tile_index + i) << "]\n";
			out << "\t\t{ //bit0\n";
			for (uint32_t y = 0; y < 8; ++y) out << "\t\t\t" << binary_literal(unique_tiles[i].bit0[y]) << ",\n";
			out << "\t\t},\n";
			out << "\t\t{ //bit1\n";
			for (uint32_t y = 0; y < 8; ++y) out << "\t\t\t" << binary_literal(unique_tiles[i].bit1[y]) << ",\n";
			out << "\t\t},\n";
			out << "\t},\n";
		}
		out << "}};\n";

		//the map itself: copy straight into ppu.background. One source line per background row,
		// row 0 = bottom (matching PPU466's background origin).
		out << "const std::array< uint16_t, " << map.size() << " > background_map = {{\n";
		for (uint32_t ty = 0; ty < PPU466::BackgroundHeight; ++ty) {
			out << "\t";
			for (uint32_t tx = 0; tx < PPU466::BackgroundWidth; ++tx) {
				out << map[tx + PPU466::BackgroundWidth*ty] << ",";
			}
			out << " //row " << ty << "\n";
		}
		out << "}};\n\n";

		next_tile_index += uint32_t(unique_tiles.size());
	}

	std::cout << "wrote asset.hpp (" << next_tile_index << " of 256 tile_table slots used)" << std::endl;
	return 0;
}
