#include <iostream>
#include <fstream>
#include <array>
#include <vector>
#include <string>

#include <glm/glm.hpp>

#include "load_save_png.hpp"
#include "PPU466.hpp"

//--------------------------------------------------------------
typedef std::array< glm::u8vec4, 4 > Palette;

const std::array< Palette, 6 > palette_table = {{
	{ //0: background
		glm::u8vec4(0x05,0x08,0x16,0xff), //space
		glm::u8vec4(0x7d,0xd3,0xfc,0xff), //atmosphere rim
		glm::u8vec4(0x16,0x4a,0x70,0xff), //ocean
		glm::u8vec4(0x5c,0x8f,0x7b,0xff), //land
	},
	{ //1: droplet
		glm::u8vec4(0x00,0x00,0x00,0x00), //transparent
		glm::u8vec4(0xae,0xb4,0xba,0xff), //grey
		glm::u8vec4(0xf4,0xf7,0xfa,0xff), //white
		glm::u8vec4(0xf4,0xf7,0xfa,0xff), //spare (dup white)
	},
	{ //2: star (small + bright)
		glm::u8vec4(0x00,0x00,0x00,0x00),
		glm::u8vec4(0xfb,0xbf,0x24,0xff), //gold
		glm::u8vec4(0xff,0xf7,0xd6,0xff), //cream
		glm::u8vec4(0xd9,0x77,0x06,0xff), //amber
	},
	{ //3: meteorite (small + large)
		glm::u8vec4(0x00,0x00,0x00,0x00),
		glm::u8vec4(0x6b,0x62,0x5c,0xff), //midgrey
		glm::u8vec4(0x2b,0x25,0x23,0xff), //darkgrey
		glm::u8vec4(0xb7,0xaa,0x9b,0xff), //rock highlight
	},
	{ //4: spacecraft body
		glm::u8vec4(0x00,0x00,0x00,0x00),
		glm::u8vec4(0x16,0x1b,0x35,0xff), //dark
		glm::u8vec4(0x65,0x73,0x8e,0xff), //bluegrey
		glm::u8vec4(0xbf,0xe3,0xea,0xff), //cyan
	},
	{ //5: spacecraft other parts
		glm::u8vec4(0x00,0x00,0x00,0x00),
		glm::u8vec4(0x16,0x1b,0x35,0xff), //dark
		glm::u8vec4(0x65,0x73,0x8e,0xff), //bluegrey
		glm::u8vec4(0xff,0xb3,0x47,0xff), //orange
	},
}};

//one asset = one PNG + the list of palette_table indices its tiles are allowed to use
struct AssetInfo {
	std::string name;
	std::string path;
	std::vector< uint8_t > candidate_palettes;
};

const std::array< AssetInfo, 6 > assets = {{
	{ "droplet",           "assets/droplet-16-16.png",            {1} },
	{ "human_spacecraft",  "assets/human-spacecraft-48-24.png",    {4, 5} },
	{ "star_small",        "assets/small-star-8-8.png",            {2} },
	{ "star_bright",       "assets/bright-star-16-16.png",         {2} },
	{ "meteorite_small",   "assets/meteorite-small-16-16.png",     {3} },
	{ "meteorite_large",   "assets/meteorite-large-24-24.png",     {3} },
}};

//--------------------------------------------------------------
//find which palette (by index into `palette_table`) can render all colors in `colors`;
// returns -1 if none of `candidates` work.
int32_t find_palette(std::vector< glm::u8vec4 > const &colors, std::vector< uint8_t > const &candidates) {
	for (uint8_t p : candidates) {
		Palette const &pal = palette_table[p];
		bool all_found = true;
		for (auto const &c : colors) {
			bool found = false;
			for (auto const &pc : pal) {
				if (pc == c) { found = true; break; }
			}
			if (!found) { all_found = false; break; }
		}
		if (all_found) return int32_t(p);
	}
	return -1;
}

//--------------------------------------------------------------
int main(int argc, char **argv) {
	std::ofstream out("asset.hpp");
	out << "#pragma once\n";
	out << "//AUTO-GENERATED by extract_sprite.cpp \n";
    out << "\n";
    out << "#include \"PPU466.hpp\" \n";

	for (auto const &asset : assets) {
		glm::uvec2 size;
		std::vector< glm::u8vec4 > pixels;
		load_png(asset.path, &size, &pixels, OriginLocation::LowerLeftOrigin);

		if (size.x % 8 != 0 || size.y % 8 != 0) {
			std::cerr << "ERROR: " << asset.path << " is " << size.x << "x" << size.y
			          << ", not a multiple of 8x8." << std::endl;
			return 1;
		}

        // if a sprite consists of multiple tiles
		uint32_t tiles_x = size.x / 8;
		uint32_t tiles_y = size.y / 8;

		out << "//" << asset.name << " (" << tiles_x << "x" << tiles_y << " tiles):\n";
		out << "const PPU466::Tile " << asset.name << "_tiles[" << (tiles_x*tiles_y) << "] = {\n";

		std::string palette_line = "const uint8_t " + asset.name + "_palettes[" + std::to_string(tiles_x*tiles_y) + "] = {";

		for (uint32_t ty = 0; ty < tiles_y; ++ty) {
			for (uint32_t tx = 0; tx < tiles_x; ++tx) {
				//gather this tile's distinct colors
				std::vector< glm::u8vec4 > used;
				for (uint32_t y = 0; y < 8; ++y) {
					for (uint32_t x = 0; x < 8; ++x) {
						glm::u8vec4 c = pixels[(tx*8+x) + size.x*(ty*8+y)];
						bool seen = false;
						for (auto const &u : used) if (u == c) { seen = true; break; }
						if (!seen) used.push_back(c);
					}
				}

				int32_t pal_index = find_palette(used, asset.candidate_palettes);
				if (pal_index < 0) {
					std::cerr << "ERROR: " << asset.path << " tile (" << tx << "," << ty << ") "
					          << "uses " << used.size() << " colors that don't fit any candidate palette."
					          << std::endl;
					return 1;
				}
				Palette const &pal = palette_table[pal_index];

				//pack pixel colors into bit0/bit1 using this tile's matched palette:
				PPU466::Tile tile;
				for (uint32_t y = 0; y < 8; ++y) {
					uint8_t bit0 = 0, bit1 = 0;
					for (uint32_t x = 0; x < 8; ++x) {
						glm::u8vec4 c = pixels[(tx*8+x) + size.x*(ty*8+y)];
						uint32_t idx = 0;
						for (; idx < 4; ++idx) if (pal[idx] == c) break;
						if (idx & 1) bit0 |= (1 << x);
						if (idx & 2) bit1 |= (1 << x);
					}
					tile.bit0[y] = bit0;
					tile.bit1[y] = bit1;
				}

				out << "  {{";
				for (auto b : tile.bit0) out << "0x" << std::hex << uint32_t(b) << ",";
				out << "}}, {{";
				for (auto b : tile.bit1) out << "0x" << std::hex << uint32_t(b) << ",";
				out << "}}},\n";
				palette_line += std::to_string(uint32_t(pal_index)) + ",";
			} //end tile
		}
		out << "};\n";
		out << palette_line << "};\n\n";
	} //end asset

	std::cout << "wrote asset.hpp" << std::endl;
	return 0;
}
