#include "PlayMode.hpp"

//tiles, palettes, and the background map, generated by extract_sprite.cpp:
#include "asset.hpp"

//for the GL_ERRORS() macro:
#include "gl_errors.hpp"

//for glm::value_ptr() :
#include <glm/gtc/type_ptr.hpp>

#include <algorithm>
#include <cassert>
#include <cmath>
#include <random>

PlayMode::PlayMode() {
	//everything below comes from asset.hpp, which extract_sprite.cpp generates
	// from the PNGs in assets/. Nothing here is hand-typed pixel data.

	{ //palettes: the generated table fills palette_table[0..5]; 6 and 7 stay unused for now.
		assert(asset_palettes.size() <= ppu.palette_table.size());
		for (uint32_t i = 0; i < asset_palettes.size(); ++i) {
			ppu.palette_table[i] = asset_palettes[i];
		}
	}

	{ //tiles: each asset was assigned a base slot in tile_table by the generator.
		auto load_tiles = [this](uint8_t base, PPU466::Tile const *tiles, size_t count) {
			assert(base + count <= ppu.tile_table.size() && "generator promised these fit.");
			for (size_t i = 0; i < count; ++i) {
				ppu.tile_table[base + i] = tiles[i];
			}
		};

		load_tiles(droplet_tile_index,          droplet_tiles.data(),          droplet_tiles.size());
		load_tiles(human_spacecraft_tile_index, human_spacecraft_tiles.data(), human_spacecraft_tiles.size());
		load_tiles(star_small_tile_index,       star_small_tiles.data(),       star_small_tiles.size());
		load_tiles(star_bright_tile_index,      star_bright_tiles.data(),      star_bright_tiles.size());
		load_tiles(meteorite_small_tile_index,  meteorite_small_tiles.data(),  meteorite_small_tiles.size());
		load_tiles(meteorite_large_tile_index,  meteorite_large_tiles.data(),  meteorite_large_tiles.size());
		load_tiles(background_tile_index,       background_tiles.data(),       background_tiles.size());
	}

	{ //entity sizes: tiles -> pixels, derived from the asset pipeline
		droplet.width  = float(droplet_tiles_x) * TileSize;          //2 tiles -> 16 px
		droplet.height = float(droplet_tiles_y) * TileSize;          //2 tiles -> 16 px
		ship.width     = float(human_spacecraft_tiles_x) * TileSize; //6 tiles -> 48 px
		ship.height    = float(human_spacecraft_tiles_y) * TileSize; //3 tiles -> 24 px
	}

	{ //background: the generated map is already in ppu.background's packed format.
		static_assert(background_map.size() == PPU466::BackgroundWidth * PPU466::BackgroundHeight,
		              "generated map covers the whole background grid.");
		std::copy(background_map.begin(), background_map.end(), ppu.background.begin());
	}
}

PlayMode::~PlayMode() {
}

//--------------------------------------------------------------
//helper functions
float PlayMode::get_speed(Speed speed) {
	switch (speed)
	{
	case Speed::Normal:
		return 40.0f;
	case Speed::Accelerated:
		return 75.0f;
	case Speed::Lightspeed:
		return 120.0f;
	default:
		assert(0 && "Speed undefined.");
		break;
	}
}
void PlayMode::Player::speed_up(bool all_the_way) {
	if (all_the_way) { droplet_speed = Speed::Lightspeed; return; }
	if (droplet_speed == Speed::Normal) { droplet_speed = Speed::Accelerated; }
	else if (droplet_speed == Speed::Accelerated) { droplet_speed = Speed::Lightspeed; }
}
void PlayMode::Player::speed_down(bool all_the_way) {
	if (all_the_way) { droplet_speed = Speed::Normal; return; }
	if (droplet_speed == Speed::Lightspeed) { droplet_speed = Speed::Accelerated; }
	else if (droplet_speed == Speed::Accelerated) { droplet_speed = Speed::Normal; }
}

void PlayMode::update_ship(float elapsed) {
	//difficulty can be changed here: 
	// smaller jitter = smarter evasion, smaller hold = more reactive.
	constexpr float JitterRadians = 0.6f;
	constexpr float DirectionHold = 0.4f;

	//hold a direction for a while
	// re-rolling every frame would just vibrate in place
	ship.direction_timer -= elapsed;
	if (ship.direction_timer <= 0.0f) {
		//flee: point away from the droplet, then jitter so it is not perfectly predictable
		glm::vec2 ship_center    = ship.ship_at + glm::vec2(ship.width, ship.height) * 0.5f;
		glm::vec2 droplet_center = droplet.droplet_at + glm::vec2(droplet.width, droplet.height) * 0.5f;
		glm::vec2 away = ship_center - droplet_center;
		if (glm::length(away) < 0.001f) away = glm::vec2(1.0f, 0.0f);
		away = glm::normalize(away);

		float t = float(mt() % 1001) / 1000.0f; //0..1
		float angle = (t * 2.0f - 1.0f) * JitterRadians;
		float c = std::cos(angle), s = std::sin(angle);
		ship.direction = glm::vec2(away.x * c - away.y * s, away.x * s + away.y * c);

		ship.direction_timer = DirectionHold;
	}

	ship.ship_at += ship.direction * get_speed(ship.ship_speed) * elapsed;

	//clamp, and stop the direction pushing further into the wall so the ship slides
	// along it instead of stopping dead (reflecting would send it back at the player).
	float max_x = float(PPU466::ScreenWidth) - ship.width;
	float max_y = float(PPU466::ScreenHeight) - ship.height;
	if (ship.ship_at.x < 0.0f)  { ship.ship_at.x = 0.0f;  ship.direction.x = std::max(0.0f, ship.direction.x); }
	if (ship.ship_at.x > max_x) { ship.ship_at.x = max_x; ship.direction.x = std::min(0.0f, ship.direction.x); }
	if (ship.ship_at.y < 0.0f)  { ship.ship_at.y = 0.0f;  ship.direction.y = std::max(0.0f, ship.direction.y); }
	if (ship.ship_at.y > max_y) { ship.ship_at.y = max_y; ship.direction.y = std::min(0.0f, ship.direction.y); }
}

void PlayMode::clamp_to_screen(glm::vec2 &at, float w, float h) {
	//avoid teleportation by avoid player/npc wrapping up
	at.x = std::max(0.0f, std::min(float(PPU466::ScreenWidth)  - w, at.x));
	at.y = std::max(0.0f, std::min(float(PPU466::ScreenHeight) - h, at.y));
}

//--------------------------------------------------------------
//main functions
bool PlayMode::handle_event(SDL_Event const &evt, glm::uvec2 const &window_size) {

	if (evt.type == SDL_EVENT_KEY_DOWN) {
		if (evt.key.key == SDLK_LEFT) {
			left.downs += 1;
			left.pressed = true;
			return true;
		} else if (evt.key.key == SDLK_RIGHT) {
			right.downs += 1;
			right.pressed = true;
			return true;
		} else if (evt.key.key == SDLK_UP) {
			up.downs += 1;
			up.pressed = true;
			return true;
		} else if (evt.key.key == SDLK_DOWN) {
			down.downs += 1;
			down.pressed = true;
			return true;
		}
	} else if (evt.type == SDL_EVENT_KEY_UP) {
		if (evt.key.key == SDLK_LEFT) {
			left.pressed = false;
			return true;
		} else if (evt.key.key == SDLK_RIGHT) {
			right.pressed = false;
			return true;
		} else if (evt.key.key == SDLK_UP) {
			up.pressed = false;
			return true;
		} else if (evt.key.key == SDLK_DOWN) {
			down.pressed = false;
			return true;
		}
	}

	return false;
}

void PlayMode::update(float elapsed) {

	{
		//Player logic
		float player_speed = get_speed(droplet.droplet_speed);
		if (left.pressed) droplet.droplet_at.x -= player_speed * elapsed;
		if (right.pressed) droplet.droplet_at.x += player_speed * elapsed;
		if (down.pressed) droplet.droplet_at.y -= player_speed * elapsed;
		if (up.pressed) droplet.droplet_at.y += player_speed * elapsed;
		clamp_to_screen(droplet.droplet_at, droplet.width, droplet.height);
	}

	{
		// Spacecraft logic
		update_ship(elapsed);
	}

	//reset button press counters:
	left.downs = 0;
	right.downs = 0;
	up.downs = 0;
	down.downs = 0;
}

void PlayMode::draw(glm::uvec2 const &drawable_size) {
	//--- set ppu state based on game state ---

	//deep space; shows through wherever background tiles are transparent:
	ppu.background_color = glm::u8vec3(0x05, 0x08, 0x16);

	//background tiles + map were installed once in the constructor; scrolling just moves
	// the window over them. Half the player's speed, so the world drifts behind the droplet.
	ppu.background_position = glm::ivec2(
		int32_t(-0.5f * droplet.droplet_at.x),
		int32_t(-0.5f * droplet.droplet_at.y)
	);

	{ //sprites: park all 64 offscreen, then place the ones we want to look at.
		for (auto &sprite : ppu.sprites) {
			sprite.y = 240; //>= 240 is offscreen
		}

		uint32_t next_sprite = 0;

		//an asset wider or taller than 8px needs one sprite per 8x8 tile;
		// tiles were generated row-major with ty = 0 at the BOTTOM.
		auto place = [&](uint8_t base_tile, uint8_t const *tile_palettes,
		                 uint32_t tiles_x, uint32_t tiles_y, glm::ivec2 const &at) {
			for (uint32_t ty = 0; ty < tiles_y; ++ty) {
				for (uint32_t tx = 0; tx < tiles_x; ++tx) {
					uint32_t i = tx + tiles_x * ty;
					assert(next_sprite < ppu.sprites.size() && "ran out of sprite slots.");
					PPU466::Sprite &sprite = ppu.sprites[next_sprite++];
					sprite.x = uint8_t(at.x + 8 * int32_t(tx));
					sprite.y = uint8_t(at.y + 8 * int32_t(ty));
					sprite.index = uint8_t(base_tile + i);
					sprite.attributes = tile_palettes[i];
				}
			}
		};

		place(droplet_tile_index, droplet_tile_palettes.data(),
		      droplet_tiles_x, droplet_tiles_y,
		      glm::ivec2(int32_t(droplet.droplet_at.x), int32_t(droplet.droplet_at.y)));

		place(human_spacecraft_tile_index, human_spacecraft_tile_palettes.data(),
		      human_spacecraft_tiles_x, human_spacecraft_tiles_y,
		      glm::ivec2(int32_t(ship.ship_at.x), int32_t(ship.ship_at.y)));

		place(star_small_tile_index, star_small_tile_palettes.data(),
		      star_small_tiles_x, star_small_tiles_y, glm::ivec2(24, 208));

		place(star_bright_tile_index, star_bright_tile_palettes.data(),
		      star_bright_tiles_x, star_bright_tiles_y, glm::ivec2(208, 200));

		place(meteorite_small_tile_index, meteorite_small_tile_palettes.data(),
		      meteorite_small_tiles_x, meteorite_small_tiles_y, glm::ivec2(40, 128));

		place(meteorite_large_tile_index, meteorite_large_tile_palettes.data(),
		      meteorite_large_tiles_x, meteorite_large_tiles_y, glm::ivec2(192, 120));
	}

	//--- actually draw ---
	ppu.draw(drawable_size);
}
