#include "PlayMode.hpp"

//tiles, palettes, and the background map, generated by extract_sprite.cpp:
#include "asset.hpp"

//for the GL_ERRORS() macro:
#include "gl_errors.hpp"

//for glm::value_ptr() :
#include <glm/gtc/type_ptr.hpp>

#include <algorithm>
#include <cassert>
#include <cmath>
#include <random>

PlayMode::PlayMode() {
	//everything below comes from asset.hpp, which extract_sprite.cpp generates
	// from the PNGs in assets/. Nothing here is hand-typed pixel data.

	{ //palettes: the generated table fills palette_table[0..5]; 6 and 7 stay unused for now.
		assert(asset_palettes.size() <= ppu.palette_table.size());
		for (uint32_t i = 0; i < asset_palettes.size(); ++i) {
			ppu.palette_table[i] = asset_palettes[i];
		}
	}

	{ //tiles: each asset was assigned a base slot in tile_table by the generator.
		auto load_tiles = [this](uint8_t base, PPU466::Tile const *tiles, size_t count) {
			assert(base + count <= ppu.tile_table.size() && "generator promised these fit.");
			for (size_t i = 0; i < count; ++i) {
				ppu.tile_table[base + i] = tiles[i];
			}
		};

		load_tiles(droplet_tile_index,          droplet_tiles.data(),          droplet_tiles.size());
		load_tiles(human_spacecraft_tile_index, human_spacecraft_tiles.data(), human_spacecraft_tiles.size());
		load_tiles(star_small_tile_index,       star_small_tiles.data(),       star_small_tiles.size());
		load_tiles(star_bright_tile_index,      star_bright_tiles.data(),      star_bright_tiles.size());
		load_tiles(meteorite_small_tile_index,  meteorite_small_tiles.data(),  meteorite_small_tiles.size());
		load_tiles(meteorite_large_tile_index,  meteorite_large_tiles.data(),  meteorite_large_tiles.size());
		load_tiles(background_tile_index,       background_tiles.data(),       background_tiles.size());
	}

	{ //entity sizes: tiles -> pixels, derived from the asset pipeline
		droplet.width  = float(droplet_tiles_x) * TileSize;          //2 tiles -> 16 px
		droplet.height = float(droplet_tiles_y) * TileSize;          //2 tiles -> 16 px
		ship.width     = float(human_spacecraft_tiles_x) * TileSize; //6 tiles -> 48 px
		ship.height    = float(human_spacecraft_tiles_y) * TileSize; //3 tiles -> 24 px
	}

	{ //pickups: fixed composition keeps the sprite cost constant and provable.
		constexpr uint32_t FixedSprites  = 4 + 18; //droplet + ship
		constexpr uint32_t PickupSprites = 2*1 + 1*4 + 6*4 + 1*9;
		static_assert(FixedSprites + PickupSprites <= 64, "sprite budget exceeded");

		uint32_t i = 0;
		for (uint32_t n = 0; n < 2; ++n) pickups[i++].kind = Pickup::Kind::SmallStar;
		pickups[i++].kind = Pickup::Kind::BrightStar;
		for (uint32_t n = 0; n < 6; ++n) pickups[i++].kind = Pickup::Kind::SmallMeteorite;
		pickups[i++].kind = Pickup::Kind::LargeMeteorite;
		assert(i == pickups.size() && "composition fills the pool exactly.");
	}

	{ //positions, timer and score: shared with the R restart path.
		reset_round();
	}

	{ //background: the generated map is already in ppu.background's packed format.
		static_assert(background_map.size() == PPU466::BackgroundWidth * PPU466::BackgroundHeight,
		              "generated map covers the whole background grid.");
		std::copy(background_map.begin(), background_map.end(), ppu.background.begin());
	}
}

PlayMode::~PlayMode() {
}

//--------------------------------------------------------------
//helper functions
float PlayMode::get_speed(Speed speed) {
	//no default: case, so a new Speed makes the compiler warn about the missing case here.
	switch (speed)
	{
	case Speed::Normal:
		return 40.0f;
	case Speed::Accelerated:
		return 75.0f;
	case Speed::Lightspeed:
		return 120.0f;
	}
	//unreachable, but every control path must return a value (MSVC C4715).
	assert(0 && "Speed undefined.");
	return 40.0f;
}
void PlayMode::Player::speed_up(bool all_the_way) {
	if (all_the_way) { droplet_speed = Speed::Lightspeed; return; }
	if (droplet_speed == Speed::Normal) { droplet_speed = Speed::Accelerated; }
	else if (droplet_speed == Speed::Accelerated) { droplet_speed = Speed::Lightspeed; }
}
void PlayMode::Player::speed_down(bool all_the_way) {
	if (all_the_way) { droplet_speed = Speed::Normal; return; }
	if (droplet_speed == Speed::Lightspeed) { droplet_speed = Speed::Accelerated; }
	else if (droplet_speed == Speed::Accelerated) { droplet_speed = Speed::Normal; }
}

void PlayMode::update_ship(float elapsed) {
	//difficulty can be changed here: 
	// smaller jitter = smarter evasion, smaller hold = more reactive.
	constexpr float JitterRadians = 0.6f;
	constexpr float DirectionHold = 0.4f;

	//the ship wraps, so the arena is more difficult for the droplets
	float max_x = float(PPU466::ScreenWidth) - ship.width;
	float max_y = float(PPU466::ScreenHeight) - ship.height;

	//hold a direction for a while
	// re-rolling every frame would just vibrate in place
	ship.direction_timer -= elapsed;
	if (ship.direction_timer <= 0.0f) {
		//flee: point away from the droplet, then jitter so it is not perfectly predictable
		glm::vec2 ship_center    = ship.ship_at + glm::vec2(ship.width, ship.height) * 0.5f;
		glm::vec2 droplet_center = droplet.droplet_at + glm::vec2(droplet.width, droplet.height) * 0.5f;

		//shortest way round: straight-line distance would send the ship fleeing into the
		// player through the seam. Forward and backward are symmetric on a torus.
		glm::vec2 away = ship_center - droplet_center;
		if (away.x >  max_x * 0.5f) away.x -= max_x;
		if (away.x < -max_x * 0.5f) away.x += max_x;
		if (away.y >  max_y * 0.5f) away.y -= max_y;
		if (away.y < -max_y * 0.5f) away.y += max_y;

		if (glm::length(away) < 0.001f) away = glm::vec2(1.0f, 0.0f);
		away = glm::normalize(away);

		float t = float(mt() % 1001) / 1000.0f; //0..1
		float angle = (t * 2.0f - 1.0f) * JitterRadians;
		float c = std::cos(angle), s = std::sin(angle);
		ship.direction = glm::vec2(away.x * c - away.y * s, away.x * s + away.y * c);

		ship.direction_timer = DirectionHold;
	}

	ship.ship_at += ship.direction * get_speed(ship.ship_speed) * elapsed;

	//wrap instead of clamping: corners were the real difficulty ceiling, since the ship
	// could only run 208px before running out of room no matter how fast it was.
	// += / -= keeps the overshoot so motion stays continuous
	if (ship.ship_at.x < 0.0f)  ship.ship_at.x += max_x;
	if (ship.ship_at.x > max_x) ship.ship_at.x -= max_x;
	if (ship.ship_at.y < 0.0f)  ship.ship_at.y += max_y;
	if (ship.ship_at.y > max_y) ship.ship_at.y -= max_y;
}

PlayMode::PickupArt PlayMode::art_for(Pickup::Kind kind) {
	PickupArt art;
	switch (kind) {
	case Pickup::Kind::SmallStar:
		art = {star_small_tile_index, star_small_tile_palettes.data(),
		       star_small_tiles_x, star_small_tiles_y, 0.0f, 0.0f};
		break;
	case Pickup::Kind::BrightStar:
		art = {star_bright_tile_index, star_bright_tile_palettes.data(),
		       star_bright_tiles_x, star_bright_tiles_y, 0.0f, 0.0f};
		break;
	case Pickup::Kind::SmallMeteorite:
		art = {meteorite_small_tile_index, meteorite_small_tile_palettes.data(),
		       meteorite_small_tiles_x, meteorite_small_tiles_y, 0.0f, 0.0f};
		break;
	case Pickup::Kind::LargeMeteorite:
		art = {meteorite_large_tile_index, meteorite_large_tile_palettes.data(),
		       meteorite_large_tiles_x, meteorite_large_tiles_y, 0.0f, 0.0f};
		break;
	}
	//no default: case above, so a new Kind warns at compile time instead of reaching
	// place() with a null palette pointer.
	assert(art.palettes != nullptr && "Pickup kind undefined.");
	art.width  = float(art.tiles_x) * TileSize;
	art.height = float(art.tiles_y) * TileSize;
	return art;
}

void PlayMode::respawn(Pickup &p) {
	PickupArt art = art_for(p.kind);
	float max_x = float(PPU466::ScreenWidth) - art.width;
	float max_y = float(PPU466::ScreenHeight) - art.height;

	//keep clear of both entities so a respawn can't be eaten on the same frame:
	constexpr float ClearRadius = 40.0f;
	for (uint32_t tries = 0; tries < 32; ++tries) {
		p.at.x = float(mt() % (uint32_t(max_x) + 1));
		p.at.y = float(mt() % (uint32_t(max_y) + 1));
		glm::vec2 center = p.at + glm::vec2(art.width, art.height) * 0.5f;
		glm::vec2 d = center - (droplet.droplet_at + glm::vec2(droplet.width, droplet.height) * 0.5f);
		glm::vec2 s = center - (ship.ship_at + glm::vec2(ship.width, ship.height) * 0.5f);
		if (glm::length(d) > ClearRadius && glm::length(s) > ClearRadius) return;
	}
	//gave up: last position stands.
}

void PlayMode::respawn_ship() {
	float max_x = float(PPU466::ScreenWidth) - ship.width;
	float max_y = float(PPU466::ScreenHeight) - ship.height;

	//a fresh ship: don't inherit the speed the last one was slowed to.
	ship.ship_speed = Speed::Accelerated;
	ship.direction_timer = 0.0f;

	//start well away from the droplet to not be caught
	constexpr float ClearRadius = 80.0f;
	for (uint32_t tries = 0; tries < 32; ++tries) {
		ship.ship_at.x = float(mt() % (uint32_t(max_x) + 1));
		ship.ship_at.y = float(mt() % (uint32_t(max_y) + 1));
		glm::vec2 d = (ship.ship_at + glm::vec2(ship.width, ship.height) * 0.5f)
		            - (droplet.droplet_at + glm::vec2(droplet.width, droplet.height) * 0.5f);
		if (glm::length(d) > ClearRadius) return;
	}
	//gave up: last position stands.
}

void PlayMode::reset_round() {
	//the constructor calls this too
	// being called at load and restart on 'R'
	droplet.droplet_at = glm::vec2(60.0f, 150.0f);
	droplet.droplet_speed = Speed::Normal;

	respawn_ship();
	for (auto &p : pickups) respawn(p);

	time_remaining = RoundSeconds;
	ships_caught = 0;
	catch_flash = 0.0f;
	won = false;
	lost = false;
}

void PlayMode::apply_pickup(Pickup::Kind kind, Speed &speed) {
	//ship methods cap at Accelerated; player methods do not.
	bool is_player = (&speed == &droplet.droplet_speed);
	switch (kind) {
	case Pickup::Kind::SmallStar:
		if (is_player) droplet.speed_up(false); else ship.speed_up();
		break;
	case Pickup::Kind::BrightStar:
		if (is_player) droplet.speed_up(true); else ship.speed_up();
		break;
	case Pickup::Kind::SmallMeteorite:
		if (is_player) droplet.speed_down(false); else ship.speed_down();
		break;
	case Pickup::Kind::LargeMeteorite:
		if (is_player) droplet.speed_down(true); else ship.speed_down();
		break;
	default:
		assert(0 && "Pickup kind undefined.");
		break;
	}
}

//AABB overlap:
static bool overlap(glm::vec2 a, float aw, float ah, glm::vec2 b, float bw, float bh) {
	return a.x < b.x + bw && b.x < a.x + aw
	    && a.y < b.y + bh && b.y < a.y + ah;
}

void PlayMode::update_pickups() {
	for (auto &p : pickups) {
		PickupArt art = art_for(p.kind);
		if (overlap(droplet.droplet_at, droplet.width, droplet.height, p.at, art.width, art.height)) {
			apply_pickup(p.kind, droplet.droplet_speed);
			respawn(p);
		} else if (overlap(ship.ship_at, ship.width, ship.height, p.at, art.width, art.height)) {
			apply_pickup(p.kind, ship.ship_speed);
			respawn(p);
		}
	}
}

void PlayMode::clamp_to_screen(glm::vec2 &at, float w, float h) {
	//avoid teleportation by avoid player/npc wrapping up
	at.x = std::max(0.0f, std::min(float(PPU466::ScreenWidth)  - w, at.x));
	at.y = std::max(0.0f, std::min(float(PPU466::ScreenHeight) - h, at.y));
}

//--------------------------------------------------------------
//main functions
bool PlayMode::handle_event(SDL_Event const &evt, glm::uvec2 const &window_size) {

	if (evt.type == SDL_EVENT_KEY_DOWN) {
		//R restarts, but only once the round is over: a mis-key must not wipe a good run
		if (evt.key.key == SDLK_R) {
			if (won || lost) reset_round();
			return true;
		}
		if (evt.key.key == SDLK_LEFT) {
			left.downs += 1;
			left.pressed = true;
			return true;
		} else if (evt.key.key == SDLK_RIGHT) {
			right.downs += 1;
			right.pressed = true;
			return true;
		} else if (evt.key.key == SDLK_UP) {
			up.downs += 1;
			up.pressed = true;
			return true;
		} else if (evt.key.key == SDLK_DOWN) {
			down.downs += 1;
			down.pressed = true;
			return true;
		}
	} else if (evt.type == SDL_EVENT_KEY_UP) {
		if (evt.key.key == SDLK_LEFT) {
			left.pressed = false;
			return true;
		} else if (evt.key.key == SDLK_RIGHT) {
			right.pressed = false;
			return true;
		} else if (evt.key.key == SDLK_UP) {
			up.pressed = false;
			return true;
		} else if (evt.key.key == SDLK_DOWN) {
			down.pressed = false;
			return true;
		}
	}

	return false;
}

void PlayMode::update(float elapsed) {
	//round is over: freeze everything, draw() shows the result color
	if (won || lost) {
		left.downs = right.downs = up.downs = down.downs = 0;
		return;
	}

	{
		//Player logic
		float player_speed = get_speed(droplet.droplet_speed);
		if (left.pressed) droplet.droplet_at.x -= player_speed * elapsed;
		if (right.pressed) droplet.droplet_at.x += player_speed * elapsed;
		if (down.pressed) droplet.droplet_at.y -= player_speed * elapsed;
		if (up.pressed) droplet.droplet_at.y += player_speed * elapsed;
		clamp_to_screen(droplet.droplet_at, droplet.width, droplet.height);
		
		//reset button press counters:
		left.downs = 0;
		right.downs = 0;
		up.downs = 0;
		down.downs = 0;
	}

	{
		// Spacecraft logic
		update_ship(elapsed);
	}

	{
		// Pickup logic
		update_pickups();
	}

	{
		// Catch a ship: score it, flash, and send out a fresh one. Only the timer ends the round.
		if (overlap(droplet.droplet_at, droplet.width, droplet.height,
		            ship.ship_at, ship.width, ship.height)) {
			++ships_caught;
			catch_flash = CatchFlashSeconds;
			respawn_ship();
		}

		if (catch_flash > 0.0f) catch_flash -= elapsed;

		time_remaining -= elapsed;
		if (time_remaining <= 0.0f) {
			time_remaining = 0.0f;
			if (ships_caught > 0) won = true; else lost = true;
		}
	}
}

void PlayMode::draw(glm::uvec2 const &drawable_size) {
	//--- set ppu state based on game state ---

	ppu.background_color = glm::u8vec3(0x05, 0x08, 0x16);

	//round result: re-tint the background palette. background_color alone would not show,
	// since every background tile is fully opaque and the map covers the whole grid.
	if (won || catch_flash > 0.0f) {
		ppu.palette_table[0] = {
			glm::u8vec4(0x06, 0x2a, 0x14, 0xff),
			glm::u8vec4(0x7d, 0xfc, 0xa0, 0xff),
			glm::u8vec4(0x16, 0x70, 0x3c, 0xff),
			glm::u8vec4(0x5c, 0xc0, 0x7b, 0xff),
		};
	} else if (lost) {
		ppu.palette_table[0] = {
			glm::u8vec4(0x2a, 0x06, 0x0a, 0xff),
			glm::u8vec4(0xfc, 0x7d, 0x88, 0xff),
			glm::u8vec4(0x78, 0x14, 0x1e, 0xff),
			glm::u8vec4(0xc0, 0x5c, 0x60, 0xff),
		};
	} else {
		ppu.palette_table[0] = asset_palettes[0];
	}

	//background tiles + map were installed once in the constructor; scrolling just moves
	// the window over them. Half the player's speed, so the world drifts behind the droplet.
	ppu.background_position = glm::ivec2(
		int32_t(-0.5f * droplet.droplet_at.x),
		int32_t(-0.5f * droplet.droplet_at.y)
	);

	{ //sprites: park all 64 offscreen, then place the ones we want to look at.
		for (auto &sprite : ppu.sprites) {
			sprite.y = 240; //>= 240 is offscreen
		}

		uint32_t next_sprite = 0;

		//an asset wider or taller than 8px needs one sprite per 8x8 tile
		// tiles were generated row-major with ty = 0 at the BOTTOM
		auto place = [this, &next_sprite](uint8_t base_tile, uint8_t const *tile_palettes,
		                                  uint32_t tiles_x, uint32_t tiles_y, glm::ivec2 const &at) {
			if (next_sprite + tiles_x * tiles_y > ppu.sprites.size()) return;
			for (uint32_t ty = 0; ty < tiles_y; ++ty) {
				for (uint32_t tx = 0; tx < tiles_x; ++tx) {
					uint32_t i = tx + tiles_x * ty;
					PPU466::Sprite &sprite = ppu.sprites[next_sprite++];
					sprite.x = uint8_t(at.x + 8 * int32_t(tx));
					sprite.y = uint8_t(at.y + 8 * int32_t(ty));
					sprite.index = uint8_t(base_tile + i);
					sprite.attributes = tile_palettes[i];
				}
			}
		};

		place(droplet_tile_index, droplet_tile_palettes.data(),
		      droplet_tiles_x, droplet_tiles_y,
		      glm::ivec2(int32_t(droplet.droplet_at.x), int32_t(droplet.droplet_at.y)));

		place(human_spacecraft_tile_index, human_spacecraft_tile_palettes.data(),
		      human_spacecraft_tiles_x, human_spacecraft_tiles_y,
		      glm::ivec2(int32_t(ship.ship_at.x), int32_t(ship.ship_at.y)));

		if (!won && !lost) {
			for (auto const &p : pickups) {
				PickupArt art = art_for(p.kind);
				place(art.tile_index, art.palettes, art.tiles_x, art.tiles_y,
				      glm::ivec2(int32_t(p.at.x), int32_t(p.at.y)));
			}
		} else {
			//score, shown the stars only here: the round is frozen
			constexpr int32_t PipSize = 10; //8px tile + 2px gap
			constexpr int32_t PipLeft = 8;
			constexpr int32_t PipTop  = int32_t(PPU466::ScreenHeight) - 16;
			int32_t per_row = (int32_t(PPU466::ScreenWidth) - 2 * PipLeft) / PipSize;

			for (uint32_t n = 0; n < ships_caught; ++n) {
				int32_t col = int32_t(n) % per_row;
				int32_t row = int32_t(n) / per_row;
				int32_t y = PipTop - row * PipSize;
				if (y < 0) break; //ran off the bottom; stop drawing
				place(star_small_tile_index, star_small_tile_palettes.data(),
				      star_small_tiles_x, star_small_tiles_y,
				      glm::ivec2(PipLeft + col * PipSize, y));
			}
		}
	}

	//--- actually draw ---
	ppu.draw(drawable_size);
}
